name: Checks

on: workflow_call

jobs:

  test-job:

    name: "Tests (Python-${{ matrix.python-version }} on ${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v3

      - name: Setup task runner
        uses: extractions/setup-just@v1

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/python-environment
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        run: just test
